openapi: 3.0.0
paths:
  /{id}:
    get:
      operationId: AppController_getHello
      parameters:
        - name: id
          required: true
          in: path
          example: 1
          schema:
            type: number
      responses:
        '200':
          description: xxxxx
          content:
            application/json:
              schema:
                type: string
      tags: []
info:
  title: Example API
  description: The API description
  version: '1.0'
  contact: {}
tags:
  - name: cats
    description: ''
servers: []
components:
  schemas: {}
